sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: j/0xvwln1vLkh8RuCZZBAEILvL2ZV7uGYNuqZzR/3cMcwdCWbVEKydP5V3V3QD019kbAauDLsTux712jIiKxmyJosmnqITL1QvZ/w0Y0DK6y2j1IV6P6XtI0gP9ui9W6Klcj24M328uptaDSyEArmPCVBm9lwG3CCn4Oy8C7IJezsnJCgyCygCxxJUxQDrzVF+6ops1rXfABjXqwJax193LJOXvzVfhqPeGD9mkcKqyt3S69Url46LGMU6isGUsfOrbIhwIyboCjzHXu14uXQHmX+112FizWyOrsJaXPEIvLWG/hHRO7kFjGb49Y/n3DyR52EhWRhfy3xDN+/vsyGviZQMMb4kG545qmbeNmV+AnqDGNXADdn11Sv1h83kNCEdqTVklA+ouk/CZKabng5E3TCmeVFHN+TMTX0mylhmDvVS5QiBnLTxgaJ4UhCSzAPrhZ7Ffyb3GvAeVVhdcjgrfhs7YllNIRRdmTJEnN6oQ+B1sPEaOnJhZG+1RismdrhnMVR42MQPM8wEPwy2q7OCFAvSJPkmnUcz92WtbLSlam9ds0Pzfs5A5hbiJZOARXJ8MY74ihFNnlA5OKZ/s3KcQODx9KWqG7G+y2yRySk02C/qqU7S44SIp76UnC8DE+lYNf0rA4ovHbi7Pfqmi4xbX2SpoGwCpg3HjWLd5ZJBo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Louise-de-la-Valliere_2710
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy